# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-06 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mykey', models.CharField(max_length=30)),
                ('value', models.TextField()),
                ('objtimestamp', django_unixdatetimefield.fields.UnixDateTimeField(editable=False)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(default='2016-11-06T10:38:21')),
            ],
            options={
                'verbose_name_plural': 'GenericObjects',
                'verbose_name': 'GenericObject',
            },
        ),
    ]
