# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-06 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('object_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericobject',
            name='objtimestamp',
            field=django_unixdatetimefield.fields.UnixDateTimeField(),
        ),
        migrations.AlterField(
            model_name='genericobject',
            name='updated_at',
            field=models.DateTimeField(default='2016-11-06T10:42:13'),
        ),
    ]
