# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-28 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericobject',
            old_name='objkey',
            new_name='mykey',
        ),
        migrations.RenameField(
            model_name='genericobject',
            old_name='objtimestamp',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='genericobject',
            old_name='objvalue',
            new_name='value',
        ),
    ]
