# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-29 15:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('object_app', '0002_auto_20161028_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericobject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 29, 15, 10, 45, 526937, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genericobject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 29, 15, 10, 54, 335455, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
