# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-29 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object_app', '0003_auto_20161029_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericobject',
            name='timestamp',
        ),
    ]
