# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-09 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_app', '0003_auto_20161106_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericobject',
            name='updated_at',
            field=models.DateTimeField(default='2016-11-09T01:24:52'),
        ),
    ]
