# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-30 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_app', '0004_remove_genericobject_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericobject',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='genericobject',
            name='updated_at',
            field=models.DateTimeField(default='2016-10-30T13:42:05'),
        ),
    ]
