# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-09 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_app', '0004_auto_20161109_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericobject',
            name='updated_at',
            field=models.DateTimeField(default='2016-11-09T01:32:59'),
        ),
    ]
